# Generated by Django 3.2.5 on 2021-09-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsstory_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsstory',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='newsstory',
            name='img_url',
            field=models.URLField(default='https://placebear.com/200/300'),
        ),
    ]
